services:
  postgres:
   image: postgres:16
   container_name: social-api-db
   environment:
    POSTGRES_DB: socialapi
    POSTGRES_USER: socialapi_user
    POSTGRES_PASSWORD: socialapi_pass
   ports:
   - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  